# Generated by Django 5.1.7 on 2025-09-25 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('location', models.CharField(default='', max_length=30)),
                ('is_working', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.store'),
        ),
    ]
