# Generated by Django 5.1.7 on 2026-03-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=30),
        ),
    ]
