# Generated by Django 5.1.7 on 2025-10-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_store_customuser_store'),
        ('management', '0047_alter_reservations_reservation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='accessed_repositories',
            field=models.ManyToManyField(blank=True, related_name='user_accessed_repositories', to='management.reposotory'),
        ),
    ]
