# Generated by Django 5.1.7 on 2025-10-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_accessed_repositories'),
        ('management', '0047_alter_reservations_reservation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='accessed_repositories',
        ),
        migrations.AddField(
            model_name='customuser',
            name='allowed_repositories',
            field=models.ManyToManyField(blank=True, related_name='user_allowed_repositories', to='management.reposotory'),
        ),
    ]
