# Generated by Django 5.1.7 on 2026-02-28 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=50)),
                ('active', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('description', models.TextField(default='')),
                ('total_available', models.IntegerField(default=0)),
                ('total_on_way', models.IntegerField(default=0)),
                ('total_requested', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reposotory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, unique=True)),
                ('location', models.CharField(default='', max_length=30)),
                ('is_working', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Add_Delete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('اضافة كمية', 'اضافة كمية'), ('اضافة مادة', 'اضافة مادة'), ('اضافة نوع من مادة', 'اضافة نوع من مادة'), ('حجز', 'حجز'), ('الغاء حجز', 'الغاء حجز'), ('تسليم', 'تسليم'), ('ارسال', 'ارسال'), ('تعديل', 'تعديل'), ('حذف', 'حذف'), ('بيع', 'بيع'), ('تغيير اسم', 'تغيير اسم'), ('مطلوب للشراء', 'مطلوب للشراء')], max_length=30)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('createAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('changer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Add_DeleteChanger', to=settings.AUTH_USER_MODEL, verbose_name='صاحب التغيير')),
                ('reader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Add_DeleteReader', to=settings.AUTH_USER_MODEL, verbose_name='قارئ الرسالة')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(default='', max_length=30, unique=True)),
                ('details', models.TextField(default='')),
                ('is_working', models.CharField(choices=[('not started yet', 'not started yet'), ('Yes', 'Yes'), ('done', 'done'), ('stopped', 'stopped')], default='not started yet', max_length=30)),
                ('createAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('EndAt', models.DateTimeField(blank=True, null=True)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Bill_seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Amounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('is_available', models.CharField(choices=[('متاح', 'متاح'), ('قيد الوصول', 'قيد الوصول'), ('محجوز', 'محجوز'), ('مخفي', 'مخفي'), ('مطلوب للشراء', 'مطلوب للشراء')], max_length=30)),
                ('product_class', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='classs', to='management.class')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='')),
                ('createAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Notification', to=settings.AUTH_USER_MODEL, verbose_name='متلقي الرسالة')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='product',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productt', to='management.product'),
        ),
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('platform', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='reposotory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='management.reposotory'),
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, unique=True)),
                ('location', models.CharField(default='', max_length=30)),
                ('is_working', models.CharField(choices=[('not started yet', 'not started yet'), ('Yes', 'Yes'), ('done', 'done'), ('stopped', 'stopped')], default='not started yet', max_length=30)),
                ('createAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('EndAt', models.DateTimeField(blank=True, null=True)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workshop_manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('createAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('EndAt', models.DateTimeField(blank=True, null=True)),
                ('reservation_type', models.CharField(choices=[('pending', 'pending'), ('delivered', 'delivered'), ('sent', 'sent'), ('cancelled', 'cancelled'), ('sold', 'sold'), ('requested for workshops', 'requested for workshops'), ('returned from workshops', 'returned from workshops')], default='', max_length=50)),
                ('used_in_workshop', models.IntegerField(blank=True, default=-1, null=True)),
                ('bill', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_reservations', to='management.bill')),
                ('newOwner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations2', to=settings.AUTH_USER_MODEL, verbose_name='صاحب الحجز الجديد')),
                ('product_class', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='management.class')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='صاحب الحجز')),
                ('workshop', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workshop_reservations', to='management.workshop')),
            ],
        ),
    ]
