# Generated by Django 5.1.7 on 2025-06-13 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Add_Delete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('اضافة', 'اضافة'), ('حجز', 'حجز'), ('الغاء حجز', 'الغاء حجز'), ('تسليم', 'تسليم')], max_length=30)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('createAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('changer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Add_DeleteChanger', to=settings.AUTH_USER_MODEL, verbose_name='صاحب التغيير')),
                ('reader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Add_DeleteReader', to=settings.AUTH_USER_MODEL, verbose_name='قارئ الرسالة')),
            ],
        ),
        migrations.CreateModel(
            name='Amounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('is_available', models.CharField(choices=[('متاح', 'متاح'), ('قيد الوصول', 'قيد الوصول'), ('محجوز', 'محجوز'), ('مخفي', 'مخفي')], max_length=30)),
                ('product_class', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='Amounts', to='management.class')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='')),
                ('createAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Notification', to=settings.AUTH_USER_MODEL, verbose_name='صاحب العقار')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='product',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Class', to='management.product'),
        ),
    ]
