# Generated by Django 5.1.7 on 2025-06-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_delete',
            name='change_type',
            field=models.CharField(choices=[('اضافة', 'اضافة'), ('حجز', 'حجز'), ('الغاء حجز', 'الغاء حجز'), ('تسليم', 'تسليم'), ('تعديل', 'تعديل')], max_length=30),
        ),
    ]
