# Generated by Django 5.1.7 on 2026-03-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_delete',
            name='createAt',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='amounts',
            name='is_available',
            field=models.CharField(choices=[('متاح', 'متاح'), ('قيد الوصول', 'قيد الوصول'), ('محجوز', 'محجوز'), ('مخفي', 'مخفي'), ('مطلوب للشراء', 'مطلوب للشراء')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='class',
            name='active',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], db_index=True, default='Yes', max_length=5),
        ),
        migrations.AlterField(
            model_name='class',
            name='type',
            field=models.CharField(db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='reposotory',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='createAt',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='reservation_type',
            field=models.CharField(choices=[('pending', 'pending'), ('delivered', 'delivered'), ('sent', 'sent'), ('cancelled', 'cancelled'), ('sold', 'sold'), ('requested for workshops', 'requested for workshops'), ('returned from workshops', 'returned from workshops')], db_index=True, default='', max_length=50),
        ),
    ]
