# Generated by Django 5.1.7 on 2026-02-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='pushtoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='EndAt',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='EndAt',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='createAt',
        ),
        migrations.AlterField(
            model_name='reservations',
            name='used_in_workshop',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='PushToken',
        ),
    ]
