# Generated by Django 5.1.7 on 2025-06-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_add_delete_change_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_delete',
            name='details',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
