# Generated by Django 5.1.7 on 2026-03-06 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_add_delete_createat_alter_amounts_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='newWorkshop',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_workshops', to='management.workshop'),
        ),
        migrations.AlterField(
            model_name='amounts',
            name='product_class',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='amounts', to='management.class'),
        ),
        migrations.AlterField(
            model_name='class',
            name='product',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='management.product'),
        ),
    ]
