# Generated by Django 5.1.7 on 2026-03-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_reservations_newworkshop_alter_amounts_product_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='createAt',
        ),
        migrations.AddField(
            model_name='reservations',
            name='finalActionTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
