# Generated by Django 5.1.7 on 2025-06-15 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_add_delete_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('reservation_kind', models.CharField(choices=[('متاح', 'متاح'), ('قيد الوصول', 'قيد الوصول'), ('محجوز', 'محجوز'), ('مخفي', 'مخفي')], max_length=30)),
                ('product_class', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='management.class')),
            ],
        ),
    ]
