# Generated by Django 5.1.7 on 2026-03-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_remove_reservations_createat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='finalActionTime',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
