# Generated by Django 5.1.7 on 2025-06-15 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_reservations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='reservation_kind',
        ),
    ]
