# Generated by Django 5.1.7 on 2026-03-12 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_reservations_finalactiontime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='Reposotory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='management.reposotory'),
        ),
        migrations.AddField(
            model_name='bill',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='user_allowed_for_bill', to=settings.AUTH_USER_MODEL),
        ),
    ]
