# Generated by Django 5.1.7 on 2026-03-13 01:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_bill_reposotory_bill_allowed_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_delete',
            name='reader',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='add_delete',
            name='reader',
            field=models.ManyToManyField(blank=True, related_name='Add_DeleteReader', to=settings.AUTH_USER_MODEL, verbose_name='قارئ الرسالة'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='Notification', to=settings.AUTH_USER_MODEL, verbose_name='متلقي الرسالة'),
        ),
    ]
