# Generated by Django 5.1.7 on 2025-06-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_reservations_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='createAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reservations',
            name='reservation_type',
            field=models.CharField(choices=[('متاح', 'متاح'), ('قيد الوصول', 'قيد الوصول'), ('محجوز', 'محجوز'), ('مخفي', 'مخفي')], default='', max_length=50),
        ),
    ]
