# Generated by Django 5.1.7 on 2025-06-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_reservations_reservation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='reservation_type',
            field=models.CharField(choices=[('حجز', 'حجز'), ('تسليم', 'تسليم'), ('الغاء حجز', 'الغاء حجز')], default='', max_length=50),
        ),
    ]
