# Generated by Django 5.1.7 on 2025-07-15 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_alter_reservations_reservation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='product',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='management.product'),
        ),
    ]
