# Generated by Django 5.1.7 on 2025-07-15 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_class_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amounts',
            name='product_class',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='product_class', to='management.class'),
        ),
    ]
