# Generated by Django 5.1.7 on 2025-07-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_alter_amounts_product_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('اضافة', 'اضافة'), ('حجز', 'حجز'), ('الغاء حجز', 'الغاء حجز'), ('تسليم', 'تسليم'), ('تعديل', 'تعديل')], max_length=50, null=True),
        ),
    ]
