# Generated by Django 5.1.7 on 2025-07-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_delete',
            name='type',
            field=models.CharField(blank=True, choices=[('متاح', 'متاح'), ('قيد الوصول', 'قيد الوصول'), ('محجوز', 'محجوز'), ('مخفي', 'مخفي')], max_length=50, null=True),
        ),
    ]
