# Generated by Django 5.1.7 on 2025-07-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_alter_add_delete_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_delete',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
