# Generated by Django 5.1.7 on 2025-07-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_alter_add_delete_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='reservation_type',
            field=models.CharField(choices=[('pending', 'pending'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='', max_length=50),
        ),
    ]
