# Generated by Django 5.1.7 on 2025-07-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_alter_reservations_reservation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_available',
            field=models.IntegerField(default=0),
        ),
    ]
