# Generated by Django 5.1.7 on 2025-07-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_product_total_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_reserved',
            field=models.IntegerField(default=0),
        ),
    ]
