# Generated by Django 5.1.7 on 2025-07-22 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_product_total_reserved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='total_reserved',
            new_name='total_on_way',
        ),
    ]
