# Generated by Django 5.1.7 on 2025-07-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_rename_total_reserved_product_total_on_way'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_delete',
            name='change_type',
            field=models.CharField(choices=[('اضافة كمية', 'اضافة كمية'), ('اضافة مادة', 'اضافة مادة'), ('اضافة نوع من مادة', 'اضافة نوع من مادة'), ('حجز', 'حجز'), ('الغاء حجز', 'الغاء حجز'), ('تسليم', 'تسليم'), ('تعديل', 'تعديل')], max_length=30),
        ),
    ]
