# Generated by Django 5.1.7 on 2025-07-25 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_alter_add_delete_change_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amounts',
            name='product_class',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='classs', to='management.class'),
        ),
        migrations.AlterField(
            model_name='class',
            name='product',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productt', to='management.product'),
        ),
    ]
