# Generated by Django 5.1.7 on 2025-08-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_alter_amounts_product_class_alter_class_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='reservation_type',
            field=models.CharField(choices=[('pending', 'pending'), ('delivered', 'delivered'), ('sent', 'sent'), ('cancelled', 'cancelled')], default='', max_length=50),
        ),
    ]
