# Generated by Django 5.1.7 on 2025-09-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_alter_reservations_reservation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='deleted',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=50),
        ),
        migrations.AlterField(
            model_name='add_delete',
            name='change_type',
            field=models.CharField(choices=[('اضافة كمية', 'اضافة كمية'), ('اضافة مادة', 'اضافة مادة'), ('اضافة نوع من مادة', 'اضافة نوع من مادة'), ('حجز', 'حجز'), ('الغاء حجز', 'الغاء حجز'), ('تسليم', 'تسليم'), ('ارسال', 'ارسال'), ('تعديل', 'تعديل')], max_length=30),
        ),
    ]
