# Generated by Django 5.1.7 on 2025-09-03 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_class_deleted_alter_add_delete_change_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='deleted',
        ),
    ]
