# Generated by Django 5.1.7 on 2025-09-25 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0024_alter_add_delete_change_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reposotory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, unique=True)),
                ('location', models.CharField(default='', max_length=30)),
                ('is_working', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
        migrations.AddField(
            model_name='class',
            name='active',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=5),
        ),
        migrations.AddField(
            model_name='reservations',
            name='newOwner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations2', to=settings.AUTH_USER_MODEL, verbose_name='صاحب الحجز الجديد'),
        ),
        migrations.AlterField(
            model_name='add_delete',
            name='change_type',
            field=models.CharField(choices=[('اضافة كمية', 'اضافة كمية'), ('اضافة مادة', 'اضافة مادة'), ('اضافة نوع من مادة', 'اضافة نوع من مادة'), ('حجز', 'حجز'), ('الغاء حجز', 'الغاء حجز'), ('تسليم', 'تسليم'), ('ارسال', 'ارسال'), ('تعديل', 'تعديل'), ('حذف', 'حذف'), ('بيع', 'بيع'), ('تغيير اسم', 'تغيير اسم')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Notification', to=settings.AUTH_USER_MODEL, verbose_name='متلقي الرسالة'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='reservation_type',
            field=models.CharField(choices=[('pending', 'pending'), ('delivered', 'delivered'), ('sent', 'sent'), ('cancelled', 'cancelled'), ('sold', 'sold')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='reposotory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='management.reposotory'),
        ),
    ]
