# Generated by Django 5.1.7 on 2025-09-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_reposotory_remove_notification_type_class_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, unique=True)),
                ('location', models.CharField(default='', max_length=30)),
                ('is_working', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=5)),
            ],
        ),
    ]
