# Generated by Django 5.1.7 on 2025-09-26 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_workshop_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workshop',
            name='product_class',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='product_class_Workshop', to='management.class'),
        ),
    ]
