# Generated by Django 5.1.7 on 2025-09-26 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0028_workshop_amount_workshop_product_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='product_class',
        ),
        migrations.CreateModel(
            name='Class_for_workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('product_class', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='product_class_Workshop', to='management.class')),
            ],
        ),
        migrations.AddField(
            model_name='workshop',
            name='classes',
            field=models.ManyToManyField(blank=True, null=True, related_name='workshop_classes', to='management.class_for_workshop'),
        ),
    ]
