# Generated by Django 5.1.7 on 2025-09-26 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0029_remove_workshop_amount_remove_workshop_product_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_for_workshop',
            name='Reposotory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='management.reposotory'),
        ),
        migrations.AddField(
            model_name='class_for_workshop',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
