# Generated by Django 5.1.7 on 2025-09-26 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0031_alter_workshop_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='manager',
        ),
    ]
