# Generated by Django 5.1.7 on 2025-09-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0033_workshop_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='amounts',
            name='type_of_work',
            field=models.CharField(choices=[('normal', 'normal'), ('workshop', 'workshop')], default='', max_length=50),
        ),
    ]
