# Generated by Django 5.1.7 on 2025-09-26 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0034_amounts_type_of_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='amounts',
            name='type_of_work',
        ),
        migrations.AddField(
            model_name='reservations',
            name='workshop',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workshop_reservations', to='management.workshop'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='Amounts',
            field=models.ManyToManyField(blank=True, null=True, related_name='workshop_amounts', to='management.amounts'),
        ),
        migrations.DeleteModel(
            name='Class_for_workshop',
        ),
    ]
