# Generated by Django 5.1.7 on 2025-09-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0035_remove_workshop_classes_remove_amounts_type_of_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='Amounts',
            field=models.ManyToManyField(blank=True, related_name='workshop_amounts', to='management.amounts'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='is_working',
            field=models.CharField(choices=[('Yes', 'Yes'), ('done', 'done'), ('stopped', 'stopped')], default='Yes', max_length=10),
        ),
    ]
