# Generated by Django 5.1.7 on 2025-09-26 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0036_alter_workshop_amounts_alter_workshop_is_working'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='Amounts',
        ),
    ]
