# Generated by Django 5.1.7 on 2025-09-26 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0037_remove_workshop_amounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='newOwner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations2', to=settings.AUTH_USER_MODEL, verbose_name='صاحب الحجز الجديد'),
        ),
    ]
