# Generated by Django 5.1.7 on 2025-10-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0038_alter_reservations_newowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='is_working',
            field=models.CharField(choices=[('not started yet', 'not started yet'), ('Yes', 'Yes'), ('done', 'done'), ('stopped', 'stopped')], default='Yes', max_length=30),
        ),
    ]
