# Generated by Django 5.1.7 on 2025-10-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0039_alter_workshop_is_working'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amounts',
            name='is_available',
            field=models.CharField(choices=[('متاح', 'متاح'), ('قيد الوصول', 'قيد الوصول'), ('محجوز', 'محجوز'), ('مخفي', 'مخفي'), ('مطلوب للشراء', 'مطلوب للشراء')], max_length=30),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='is_working',
            field=models.CharField(choices=[('not started yet', 'not started yet'), ('Yes', 'Yes'), ('done', 'done'), ('stopped', 'stopped')], default='not started yet', max_length=30),
        ),
    ]
