# Generated by Django 5.1.7 on 2025-10-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0040_alter_amounts_is_available_alter_workshop_is_working'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='reservation_type',
            field=models.CharField(choices=[('pending', 'pending'), ('delivered', 'delivered'), ('sent', 'sent'), ('cancelled', 'cancelled'), ('sold', 'sold'), ('requested for workshops', 'requested for workshops')], default='', max_length=50),
        ),
    ]
