# Generated by Django 5.1.7 on 2025-10-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0042_product_total_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_delete',
            name='change_type',
            field=models.CharField(choices=[('اضافة كمية', 'اضافة كمية'), ('اضافة مادة', 'اضافة مادة'), ('اضافة نوع من مادة', 'اضافة نوع من مادة'), ('حجز', 'حجز'), ('الغاء حجز', 'الغاء حجز'), ('تسليم', 'تسليم'), ('ارسال', 'ارسال'), ('تعديل', 'تعديل'), ('حذف', 'حذف'), ('بيع', 'بيع'), ('تغيير اسم', 'تغيير اسم'), ('مطلوب للشراء', 'مطلوب للشراء')], max_length=30),
        ),
    ]
