# Generated by Django 5.1.7 on 2025-10-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0043_alter_add_delete_change_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='used_in_workshop',
            field=models.IntegerField(default=0),
        ),
    ]
