# Generated by Django 5.1.7 on 2025-10-04 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0044_reservations_used_in_workshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='used_in_workshop',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
