# Generated by Django 5.1.7 on 2025-10-04 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0045_alter_reservations_used_in_workshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_delete',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
