# Generated by Django 5.1.7 on 2025-10-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0046_alter_add_delete_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='reservation_type',
            field=models.CharField(choices=[('pending', 'pending'), ('delivered', 'delivered'), ('sent', 'sent'), ('cancelled', 'cancelled'), ('sold', 'sold'), ('requested for workshops', 'requested for workshops'), ('returned from workshops', 'returned from workshops')], default='', max_length=50),
        ),
    ]
