from django.urls import path
from . import views

urlpatterns = [
    path('home/', views.home, name='home'),
    path('homeRead/', views.homeRead, name='homeRead'),
    path('home_for_reposotory_workshop/', views.home_for_reposotory_workshop, name='home_for_reposotory_workshop'),

    path('myStore/', views.myStore, name='myStore'),
    path('product_details/', views.product_details, name='product_details'),
    path('product_types/', views.product_types, name='product_types'),
    path('notification/', views.notification, name='notification'),
    path('register-push-token/', views.register_push_token, name='register_push_token'),
    path('unregister-push-token/', views.unregister_push_token, name='unregister_push_token'),
    path('add_class/', views.add_class, name='add_class'),
    path('add_product/', views.add_product, name='add_product'),
    path('changetype/', views.changetype, name='changetype'),
    path('history_changes/', views.history_changes, name='history_changes'),
    path('reserve/', views.reserve, name='reserve'),
    path('newreservation/', views.newreservation, name='newreservation'),
    path('settings/', views.settings, name='settings'),
    path('is_staff/', views.is_staff, name='is_staff'),
    path('cancle_reservation/', views.cancle_reservation, name='cancle_reservation'),
    path('confirm_reservation/', views.confirm_reservation, name='confirm_reservation'),
    path('confirm_requested_reservation/', views.confirm_requested_reservation, name='confirm_requested_reservation'),

    path('send_reservation/', views.send_reservation, name='send_reservation'),
    path('send_requested_reservation/', views.send_requested_reservation, name='send_requested_reservation'),
    path('edit_product_name/', views.edit_product_name, name='edit_product_name'),
    path('edit_product/', views.edit_product_name, name='edit_product'),

    path('search/', views.search_materials, name='search-materials'),
    path('class_type_name/', views.class_type_name, name='class_type_name'),
    path('class_type_delete/', views.class_type_delete, name='class_type_delet'),
    path('addReposotories/', views.addReposotory, name='addReposotories'),
    path('reposotories/', views.reposotory, name='reposotories'),
    path('turnResevation/', views.turnResevation, name='turnResevation'),
    path('confirmTurnResevation/', views.confirmTurnResevation, name='confirmTurnResevation'),
    path('cancelTurnResevation/', views.cancelTurnResevation, name='cancelTurnResevation'),
    path('sell/', views.sell, name='sell'),
    path('reposotories/toggle-status/', views.reposotoryToggleStatusView, name='reposotories-user'),
    path('workshops/', views.workshops, name='workshops'),
    path('addWorkshop/', views.addWorkshop, name='addWorkshop'),
    path('addClassToWorkshop/', views.addClassToWorkshop, name='addClassToWorkshop'),
    path('Assign_manager_Workshop/', views.Assign_manager_Workshop, name='Assign_manager_Workshop'),
    path('Workshop_details/', views.Workshop_details, name='Workshop_details'),
    path('WorkshopToggleStatusView/', views.WorkshopToggleStatusView, name='WorkshopToggleStatusView'),
    path('reposotories_for_workshop/', views.reposotories_for_workshop, name='reposotories_for_workshop'),
    path('end_workshop/', views.end_workshop, name='end_workshop'),
    path('unused_amount/', views.unused_amount, name='unused_amount'),
    path('user-allowed-repositories/<int:user_id>/', views.user_allowed_repositories, name='user_allowed_repositories'),
    path('ended_workshops/', views.ended_workshops, name='ended_workshops'),
    path('turn_Reservation_to_workshops/', views.turn_Reservation_to_workshops, name='turn_Reservation_to_workshops'),
    path('workshops_has_manager/', views.workshops_has_manager, name='workshops_has_manager'),
    path('edit_amount_in_reservation/', views.edit_amount_in_reservation, name='edit_amount_in_reservation'),
    path('reposotory_for_showing/', views.reposotory_for_showing, name='reposotory_for_showing'),
    path('end_bill/', views.end_bill, name='end_bill'),
    path('bill_details/', views.bill_details, name='bill_details'),
    path('ended_bills/', views.ended_bills, name='ended_bills'),
    path('bills/', views.bills, name='bills'),
    path('addClassToBill/', views.addClassToBill, name='addClassToBill'),
    path('addBill/', views.addBill, name='addBill'),
    path('reposotories_for_bill/', views.reposotories_for_bill, name='reposotories_for_bill'),
    path('home_for_reposotory_bill/', views.home_for_reposotory_bill, name='home_for_reposotory_bill'),
    path('cancle_requested_reservation/', views.cancle_requested_reservation, name='cancle_requested_reservation'),
    path('edit_bill/',views.edit_bill,name='edit_bill'),

path('my_script',views.my_script,name='my_script'),

]